### ISSUE TITLE
Why it is not available in fdroid main version

### ISSUE THREAD

**Issue by Pranab009** [ioliteis/projectoffline_calculator#15]
Please available it in fdroid.

**Comment by ioliteis** [comment]
Sorry for late replying.

To be honest, **I have no intention of adding them to fdroid's main repo** because that way is very complicated for me and I finish developing them.

Though these "Project Offline" apps are no longer maintained, You can still install them via [izzyondroid repo](https://android.izzysoft.de/repo).
